apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-prod-central
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/akuity/guestbook:v0.0.1
        name: guestbook
        ports:
        - containerPort: 3000
          name: http
