apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-world-sa
  namespace: guestbook-dev
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
