apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ab-test-a
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
  verification:
    analysisTemplates:
      - name: pokemon-xp
    args:
      - name: pokemon
        value: pikachu
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ab-test-b
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

  verification:
    analysisTemplates:
      - name: pokemon-xp
    args:
      - name: pokemon
        value: pikachu
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - ab-test-a
          - ab-test-b
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-west
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - prod
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-central
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - prod
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-east
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - prod
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
